import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import * as cheerio from "cheerio";
import Cities from "../components/Cities";
import Nav from "../components/Nav";

export default function Home({ dataArray }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Where is home?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav />
      <main className={styles.main}>
        <h1 className={styles.title}>Where is home?</h1>

        <Cities dataArray={dataArray} />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}

export async function getStaticProps() {
  let url =
    process.env.ENVIRONMENT === "dev"
      ? "http://localhost:3000/api/data"
      : "https://gorgeous-meerkat-3dd227.netlify.app/api/data";
  const res = await fetch(url);
  const body = await res.json();
  let dataArray = body;

  return { props: { dataArray } };
}
